# Generated by Django 5.1.1 on 2024-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="highest_temp",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="lowest_temp",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="sunrise",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="sunset",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="condition",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(),
        ),
    ]
