# Generated by Django 5.1.1 on 2024-09-21 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_weatherdata_highest_temp_weatherdata_lowest_temp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="sunrise",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="sunset",
        ),
    ]
