# Generated by Django 5.1.1 on 2024-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_remove_weatherdata_sunrise_remove_weatherdata_sunset"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="feels_like",
            field=models.FloatField(null=True),
        ),
    ]
